### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria-relay-playground#2]
I was thinking maybe it would be a good idea to deploy this project to heroku under `try-relay.sangria-graphql.org`, for instance?

I also would like to propose to put this repo in https://github.com/sangria-graphql organisation. This would make it easier for other people to discover it. Also it would be easier for us to collaborate on this project in future. I sure there would be changes and improvements in future as relay and sangria are growing pretty fast :) There are some things that can improve now, but as it is I think the project is a very good start.

Let me know if you are interested in this proposition  ;)

**Comment by yasserkaddour** [comment]
Of course you can! It will be my pleasure, thanks.
I am sorry for the late response i was very taken.

**Comment by OlegIlyenko** [comment]
Great! Really glad to that you are interested as well! 

 You are the only person who can transfer the repo in the organisation. I sent you an invitation to join **sangria-graphql** org. After you accept it, you should be able to transfer the repo in to the Github organisation: here are some docs on this: https://help.github.com/articles/transferring-a-repository/#to-transfer-a-repository-to-another-user-account

**Comment by OlegIlyenko** [comment]
Great! Transfer is complete. You should have full access to this repo, as before. And now you are a member for sangria-graphql organization. Congrats! :) 

Please let me know if something is not right (This is the first I'm doing this kind of stuff, so there is a lot of room for a human error :).

**Comment by yasserkaddour** [comment]
I am honored by your invitation, I am looking forward to contributing more to Sangria and its ecosystem.

It's also the first time to me, but so far everything seems okay.

Thank again.

Mit freundlichen Gruessen.

**Comment by OlegIlyenko** [comment]
tada :) http://try-relay.sangria-graphql.org :tada: 

(if you can't see it yet, then it's probably because of the DNS records - you just need to wait a bit)

**Comment by yasserkaddour** [comment]
Yes!!!!!! Perfect !!!! :clap:
